server:
  port: 7070
spring:
  datasource:
    password: ${POSTGRES_PASSWORD:prod123!}
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:production}
    username: ${POSTGRES_USER:prod}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          #          max-attempts: 3
          max-interval: 100
          multiplier: 2
    host: ${RABBIT_HOST:localhost}
  main:
    allow-bean-definition-overriding: true
prod:
  card:
    url: ${PROD_CARD_URL:http://localhost:7080/production/card}
    item:
      url: ${PROD_CARD_ITEM_URL:http://localhost:7080/prod/card/item}
basic:
  auth: ${BASIC_AUTH:Basic Kzc3NjIxMTAwMDAxOjEyM3F3ZTEyM1FXRQ==}
management:
  endpoint:
    health:
      show-details: always
